name: Update CV

on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

jobs:
  updatecv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update CV
        env:
          CV_GDRIVE_DOWNLOAD_URL: ${{ secrets.CV_GDRIVE_DOWNLOAD_URL }}
          CV_DROPBOX_DOWNLOAD_URL: ${{ secrets.CV_DROPBOX_DOWNLOAD_URL }}
        run: bash .scripts/update_cv.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            public/cv_joao_portela.pdf
          commit-message: |
            Auto-update CV from GDrive/Dropbox
          title: |
            Auto-update CV from GDrive/Dropbox
          branch: auto-update-cv
