name: Update CV

on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updatecv:
    runs-on: ubuntu-latest
    steps:
      - name: pwd and ls
        run: ls ; pwd
      - name: Update CV
        run: bash .scripts/update_cv.sh
